# Generated by Django 2.2 on 2019-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offset',
            field=models.IntegerField(default=0),
        ),
    ]
